# Generated by Django 5.2.7 on 2025-10-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0005_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('book_name', models.CharField(max_length=100)),
                ('any_message', models.CharField(max_length=100)),
            ],
        ),
    ]
