# Generated by Django 5.2.7 on 2025-10-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0006_book_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='book_request',
            name='any_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
